kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-sc-ext4-no-args
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: dsp.csi.daterainc.io
parameters:
  replica_count: "2"
  csi.storage.k8s.io/fstype: ext4
