apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-restore
  namespace: default
spec:
  storageClassName: dat-block-storage
  dataSource:
    name: csi-pvc-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
