apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-xfs-no-args
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-sc-xfs-no-args
