apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iscsi
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: iscsi
  template:
    metadata:
      labels:
        app: iscsi
    spec:
      hostNetwork: true
      containers:
      - name: iscsid
        imagePullPolicy: Always
        image: "dateraiodev/iscsi:v1.0.0"
        command: [ "iscsid-run.sh" ]
        securityContext:
          privileged: true
        volumeMounts:
          mountPath: "/dev"
      volumes:
      - name: dev
        hostPath:
          path: "/dev"
