apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iscsi
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: iscsi
  template:
    metadata:
      labels:
        app: iscsi
    spec:
      hostNetwork: true
      containers:
      - name: iscsid
        imagePullPolicy: Always
        image: dateraiodev/iscsi:latest
        command: [ "/bin/bash", "-c", "iscsi-recv &2>1 & iscsid-run.sh" ]
        securityContext:
          privileged: true
        volumeMounts:
          - name: devices
            mountPath: /dev
          - name: iscsi-socket
            mountPath: /iscsi-socket
          - name: libmod
            mountPath: /lib/modules
      volumes:
      - name: devices
        hostPath:
          path: /dev
      - name: iscsi-socket
        hostPath:
          path: /var/lib/iscsi-socket
          type: DirectoryOrCreate
      - name: libmod
        hostPath:
          path: /lib/modules
