apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-static-pv
  namespace: test-csi
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  csi:
    nodePublishSecretRef:
      name: ""
      namespace: ""
    driver: dsp.csi.daterainc.io
    volumeHandle: my-existing-test-vol
    volumeAttributes:
      replica_count: "3"
